const API='https://hook.eu1.make.com/tax8ujni3jgbfjsz7hi7vq1bd7uxxshc';
const names={d:['Dashboard','Przegląd sprzedaży'],i:['AI Inbox','Odpowiedzi do akceptacji'],l:['Leady','Pipeline i scoring'],u:['Automatyzacje','Procesy w tle'],s:['Ustawienia','Kontrola AI']};
let liveLeads=[],currentLead=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function go(v){document.querySelectorAll('.v').forEach(e=>e.classList.remove('on'));document.querySelectorAll('.n button').forEach(e=>e.classList.toggle('on',e.dataset.v==v));document.getElementById(v).classList.add('on');t.textContent=names[v][0];sub.textContent=names[v][1]}
function decode64(value){const clean=value.replace(/\s/g,'');const bytes=Uint8Array.from(atob(clean),c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function parseRecord(text,path){const get=label=>{const m=text.match(new RegExp('^'+label+':\\s*(.*)$','mi'));return m?m[1].trim():'—'};const d=text.match(/SZKIC ODPOWIEDZI:\s*([\s\S]*?)\nMESSENGER:/i);return{path,text,name:get('IMIĘ'),company:get('FIRMA'),email:get('E-MAIL'),phone:get('TELEFON'),source:get('ŹRÓDŁO'),message:get('WIADOMOŚĆ'),draft:d?d[1].trim():'',status:get('STATUS')}}
async function api(params,method='GET'){const key=sessionStorage.getItem('flowpilot_operator_key')||'';if(method==='GET'){const res=await fetch(API+'?'+new URLSearchParams({...params,key}));if(!res.ok)throw new Error(res.status===401?'Nieprawidłowy klucz operatora':'Błąd API '+res.status);return res.json()}const body=new URLSearchParams({...params,key});const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!res.ok)throw new Error('Błąd zapisu decyzji');return res.json()}
async function loadProduction(key){authError.textContent='';if(key)sessionStorage.setItem('flowpilot_operator_key',key);syncState.textContent='Łączenie…';const files=await api({action:'list'});const records=files.filter(f=>f.name.endsWith('-record.txt')).sort((a,b)=>b.name.localeCompare(a.name)).slice(0,20);liveLeads=await Promise.all(records.map(async f=>{const data=await api({action:'get',path:f.path});return parseRecord(decode64(data.content),f.path)}));renderProduction();auth.classList.remove('on');syncState.textContent='Dane produkcyjne';syncState.classList.add('live');prodState.textContent='✓ Połączono · '+liveLeads.length+' rekordów';return true}
function renderProduction(){newCount.textContent=liveLeads.length;approvalCount.textContent=liveLeads.filter(x=>/OCZEKUJE/i.test(x.status)).length;rows.innerHTML=liveLeads.length?liveLeads.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.company)}</td><td>—</td><td>Do akceptacji</td></tr>`).join(''):'<tr><td colspan="4" class="empty">Brak leadów</td></tr>';conversationList.innerHTML='<h3>Rozmowy produkcyjne</h3>'+(liveLeads.length?liveLeads.map((x,i)=>`<div class="cv${i===0?' on':''}" data-live="${i}"><b>${esc(x.name)}</b><div class="m">${esc(x.source)} · ${esc(x.company)}</div></div>`).join(''):'<div class="empty">Brak leadów</div>');conversationList.querySelectorAll('[data-live]').forEach(el=>el.onclick=()=>selectLead(Number(el.dataset.live)));if(liveLeads.length)selectLead(0)}
function selectLead(i){currentLead=liveLeads[i];conversationList.querySelectorAll('.cv').forEach((el,n)=>el.classList.toggle('on',n===i));who.textContent=currentLead.name;clientMessage.textContent='Klient: '+currentLead.message;leadMeta.textContent=currentLead.company+' · '+currentLead.email;r.value=currentLead.draft;ms.textContent=''}
async function decide(status){if(!currentLead){ms.textContent='Najpierw połącz dane produkcyjne.';return}ms.textContent='Zapisywanie…';try{await api({action:'approve',draft:`STATUS: ${status}\nREKORD: ${currentLead.path}\nSZKIC: ${r.value}`},'POST');ms.textContent=status==='ZATWIERDZONO'?'✓ Zatwierdzono — wiadomość nie została wysłana.':'Odrzucono — wiadomość nie została wysłana.'}catch(e){ms.textContent=e.message}}
function showAuth(){operatorKey.value='';authError.textContent='';auth.classList.add('on');setTimeout(()=>operatorKey.focus(),50)}
document.querySelectorAll('.n button').forEach(b=>b.onclick=()=>go(b.dataset.v));
document.querySelectorAll('.cv').forEach(c=>c.onclick=()=>{document.querySelectorAll('.cv').forEach(q=>q.classList.remove('on'));c.classList.add('on');who.textContent=c.dataset.n;r.value=c.dataset.n[0]=='A'?'Dzień dobry, przygotujemy ofertę dla 3-osobowego zespołu. Z jakiego kanału macie najwięcej leadów?':c.dataset.n[0]=='R'?'Tak, możemy połączyć FlowPilot z CRM przez Make/API. Jaki system Państwo używają?':'Dzień dobry, możemy zadzwonić jutro o 14:30. Jeśli pasuje, zarezerwuję termin.'});
ap.onclick=()=>currentLead?decide('ZATWIERDZONO'):ms.textContent='✓ Zatwierdzono w trybie demo.';rj.onclick=()=>currentLead?decide('ODRZUCONO'):ms.textContent='Odrzucono w trybie demo.';rg.onclick=()=>r.value='Dzień dobry! Czy jutro o 14:30 pasuje na krótką rozmowę o FlowPilot?';sv.onclick=()=>saved.textContent='✓ Zapisano';nl.onclick=()=>mo.classList.add('on');x.onclick=()=>mo.classList.remove('on');ad.onclick=()=>{rows.insertAdjacentHTML('afterbegin','<tr><td>'+esc(nn.value||'Nowy lead')+'</td><td>'+esc(cc.value||'—')+'</td><td>50</td><td>Nowy</td></tr>');mo.classList.remove('on');go('l')};
sync.onclick=showAuth;connectData.onclick=showAuth;authCancel.onclick=()=>auth.classList.remove('on');authConnect.onclick=async()=>{try{await loadProduction(operatorKey.value.trim())}catch(e){sessionStorage.removeItem('flowpilot_operator_key');authError.textContent=e.message;syncState.textContent='Dane demo'}};operatorKey.onkeydown=e=>{if(e.key==='Enter')authConnect.click()};
if(sessionStorage.getItem('flowpilot_operator_key'))loadProduction().catch(()=>sessionStorage.removeItem('flowpilot_operator_key'));

