import {createClient} from 'npm:@supabase/supabase-js@2';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Cache-Control':'no-store'},J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,'content-type':'application/json'}});
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});try{
 const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}}),jwt=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,''),{data:u}=await db.auth.getUser(jwt);if(!u.user)return J({error:'unauthorized'},401);const{data:p}=await db.from('profiles').select('organization_id').eq('id',u.user.id).single();if(!p?.organization_id)return J({error:'profile_missing'},404);const org=p.organization_id;
 if(req.method==='POST'){
  const b=await req.json().catch(()=>({}));if(!b.lead_id)return J({error:'lead_id_required'},400);const{data:l}=await db.from('leads').select('id,pipeline_stage').eq('id',String(b.lead_id)).eq('organization_id',org).single();if(!l)return J({error:'lead_not_found'},404);if(['won','lost'].includes(String(l.pipeline_stage)))return J({error:'lead_closed'},409);
  const when=b.when?new Date(b.when):new Date(Date.now()+24*3600*1000);if(Number.isNaN(when.getTime()))return J({error:'invalid_date'},400);if(when.getTime()<Date.now()-60_000)return J({error:'date_in_past'},400);
  const{error}=await db.from('leads').update({next_follow_up_at:when.toISOString(),updated_at:new Date().toISOString()}).eq('id',l.id).eq('organization_id',org);if(error)return J({error:'schedule_failed'},500);
  await db.from('activity_log').insert({organization_id:org,actor_user_id:u.user.id,event_type:'followup.scheduled',entity_type:'lead',entity_id:l.id,data:{when:when.toISOString()}});return J({ok:true,when:when.toISOString()});
 }
 if(req.method!=='GET')return J({error:'method_not_allowed'},405);
 const now=new Date(),end=new Date();end.setHours(23,59,59,999);const{data:leads,error}=await db.from('leads').select('id,contact_id,status,score,intent,recommended_action,pipeline_stage,estimated_value,next_follow_up_at,updated_at').eq('organization_id',org).not('pipeline_stage','in','(won,lost)').order('score',{ascending:false});if(error)return J({error:'load_failed'},500);
 const ids=[...new Set((leads||[]).map((x:any)=>x.contact_id).filter(Boolean))];let contacts:any[]=[];if(ids.length){const r=await db.from('contacts').select('id,name').in('id',ids);contacts=r.data||[]}const cm=Object.fromEntries(contacts.map((x:any)=>[x.id,x.name||'Klient']));const items=(leads||[]).map((x:any)=>{const due=x.next_follow_up_at?new Date(x.next_follow_up_at)<=end:false,overdue=x.next_follow_up_at?new Date(x.next_follow_up_at)<now:false;let priority=Number(x.score||0);if(overdue)priority+=1000;else if(due)priority+=500;if(['decision','negotiation'].includes(x.pipeline_stage||x.status))priority+=100;if(['offer','proposal'].includes(x.pipeline_stage||x.status))priority+=70;return{...x,contact_name:cm[x.contact_id]||'Klient',due,overdue,priority}}).sort((a:any,b:any)=>b.priority-a.priority);
 const notifications=items.filter((x:any)=>x.due||Number(x.score||0)>=70).slice(0,20).map((x:any)=>({type:x.overdue?'overdue_followup':x.due?'followup_today':'hot_lead',lead_id:x.id,title:x.overdue?'Zaległy follow-up':x.due?'Follow-up na dziś':'Gorący lead',contact_name:x.contact_name,score:x.score,action:x.recommended_action||'Skontaktuj się z klientem',when:x.next_follow_up_at}));return J({queue:items.filter((x:any)=>x.due).slice(0,20),notifications,counts:{due:items.filter((x:any)=>x.due).length,overdue:items.filter((x:any)=>x.overdue).length,hot:items.filter((x:any)=>Number(x.score||0)>=70).length}});
}catch(e){return J({error:'internal_error'},500)}});
